// Form data utilities for dropdowns and select fields

// US States with abbreviations
export const US_STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
];

// Canadian Provinces and Territories
export const CANADIAN_PROVINCES = [
  { value: 'AB', label: 'Alberta' },
  { value: 'BC', label: 'British Columbia' },
  { value: 'MB', label: 'Manitoba' },
  { value: 'NB', label: 'New Brunswick' },
  { value: 'NL', label: 'Newfoundland and Labrador' },
  { value: 'NS', label: 'Nova Scotia' },
  { value: 'NT', label: 'Northwest Territories' },
  { value: 'NU', label: 'Nunavut' },
  { value: 'ON', label: 'Ontario' },
  { value: 'PE', label: 'Prince Edward Island' },
  { value: 'QC', label: 'Quebec' },
  { value: 'SK', label: 'Saskatchewan' },
  { value: 'YT', label: 'Yukon' },
];

// Combined US States and Canadian Provinces for state/province dropdown
export const STATES_AND_PROVINCES = [
  ...US_STATES.map(s => ({ ...s, category: 'US State' as const })),
  ...CANADIAN_PROVINCES.map(p => ({ ...p, category: 'Canadian Province' as const })),
  { value: 'OTHER', label: 'Other', category: 'Other' as const },
];

// ISO Country Codes (common ones for North America and international)
export const COUNTRY_CODES = [
  { value: 'US', label: 'United States (US)' },
  { value: 'CA', label: 'Canada (CA)' },
  { value: 'MX', label: 'Mexico (MX)' },
  { value: 'GB', label: 'United Kingdom (GB)' },
  { value: 'AU', label: 'Australia (AU)' },
  { value: 'DE', label: 'Germany (DE)' },
  { value: 'FR', label: 'France (FR)' },
  { value: 'IT', label: 'Italy (IT)' },
  { value: 'ES', label: 'Spain (ES)' },
  { value: 'NL', label: 'Netherlands (NL)' },
  { value: 'BE', label: 'Belgium (BE)' },
  { value: 'CH', label: 'Switzerland (CH)' },
  { value: 'AT', label: 'Austria (AT)' },
  { value: 'SE', label: 'Sweden (SE)' },
  { value: 'NO', label: 'Norway (NO)' },
  { value: 'DK', label: 'Denmark (DK)' },
  { value: 'FI', label: 'Finland (FI)' },
  { value: 'IE', label: 'Ireland (IE)' },
  { value: 'PT', label: 'Portugal (PT)' },
  { value: 'GR', label: 'Greece (GR)' },
  { value: 'PL', label: 'Poland (PL)' },
  { value: 'CZ', label: 'Czech Republic (CZ)' },
  { value: 'HU', label: 'Hungary (HU)' },
  { value: 'RO', label: 'Romania (RO)' },
  { value: 'BG', label: 'Bulgaria (BG)' },
  { value: 'HR', label: 'Croatia (HR)' },
  { value: 'SI', label: 'Slovenia (SI)' },
  { value: 'SK', label: 'Slovakia (SK)' },
  { value: 'EE', label: 'Estonia (EE)' },
  { value: 'LV', label: 'Latvia (LV)' },
  { value: 'LT', label: 'Lithuania (LT)' },
  { value: 'JP', label: 'Japan (JP)' },
  { value: 'CN', label: 'China (CN)' },
  { value: 'IN', label: 'India (IN)' },
  { value: 'KR', label: 'South Korea (KR)' },
  { value: 'SG', label: 'Singapore (SG)' },
  { value: 'HK', label: 'Hong Kong (HK)' },
  { value: 'TW', label: 'Taiwan (TW)' },
  { value: 'TH', label: 'Thailand (TH)' },
  { value: 'MY', label: 'Malaysia (MY)' },
  { value: 'ID', label: 'Indonesia (ID)' },
  { value: 'PH', label: 'Philippines (PH)' },
  { value: 'VN', label: 'Vietnam (VN)' },
  { value: 'BR', label: 'Brazil (BR)' },
  { value: 'AR', label: 'Argentina (AR)' },
  { value: 'CL', label: 'Chile (CL)' },
  { value: 'CO', label: 'Colombia (CO)' },
  { value: 'PE', label: 'Peru (PE)' },
  { value: 'ZA', label: 'South Africa (ZA)' },
  { value: 'EG', label: 'Egypt (EG)' },
  { value: 'IL', label: 'Israel (IL)' },
  { value: 'AE', label: 'United Arab Emirates (AE)' },
  { value: 'SA', label: 'Saudi Arabia (SA)' },
  { value: 'TR', label: 'Turkey (TR)' },
  { value: 'RU', label: 'Russia (RU)' },
  { value: 'NZ', label: 'New Zealand (NZ)' },
];

// Common Industries
export const INDUSTRIES = [
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'fertility_clinic', label: 'Fertility Clinic' },
  { value: 'medical_practice', label: 'Medical Practice' },
  { value: 'hospital', label: 'Hospital' },
  { value: 'reproductive_medicine', label: 'Reproductive Medicine' },
  { value: 'ivf_center', label: 'IVF Center' },
  { value: 'obstetrics_gynecology', label: 'Obstetrics & Gynecology' },
  { value: 'urology', label: 'Urology' },
  { value: 'laboratory', label: 'Laboratory' },
  { value: 'cryobank', label: 'Cryobank' },
  { value: 'biotech', label: 'Biotechnology' },
  { value: 'pharmaceutical', label: 'Pharmaceutical' },
  { value: 'medical_device', label: 'Medical Device' },
  { value: 'health_services', label: 'Health Services' },
  { value: 'other', label: 'Other' },
];

